L0_MAP_WIDTH	= 32
L0_MAP_HEIGHT	= 32
L1_MAP_WIDTH	= 64
L1_MAP_HEIGHT	= 32

VIEWPORT_WIDTH	= 28
VIEWPORT_HEIGHT	= 28

TERRAIN_MAP_WIDTH = 1024		; code in s_lander require this be multiple of 256

TERRAIN_HEIGHT_ADDR = $A000
TERRAIN_CHAR_ADDR	= (TERRAIN_HEIGHT_ADDR + TERRAIN_MAP_WIDTH)
TERRAIN_ORE_ADDR	= (TERRAIN_CHAR_ADDR + TERRAIN_MAP_WIDTH)

; Terrain tile map codes
BRICK_NONE		= $20
BRICK_SOLID		= $21
BRICK_LEFT		= $22
BRICK_RIGHT		= $23
BRICK_TOP		= $24
BRICK_PIT		= $25

JOY_UP			= $08
JOY_DOWN		= $04
JOY_LEFT		= $02
JOY_RIGHT		= $01
JOY_CTRL		= $80
JOY_ALT			= $40
JOY_SPACE		= $20
JOY_ENTER		= $10